language: cpp
matrix:
    include:
    - os: linux
      dist: trusty
#     - os: osx 
#       osx_image: xcode8.2
#     - os: osx 
#       osx_image: xcode8
#     - os: osx 
#       osx_image: xcode7.3
#     - os: osx 
#       osx_image: xcode6.4

sudo: true

notifications:
    email: false

install: 
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda install gcc zlib boost
    - conda install -c asmeurer gsl
    - conda install -c bioconda libsequence
script:
    - export LD_LIBRARY_PATH=$HOME/miniconda/lib
    - export CPPFLAGS="-I$HOME/miniconda/include $CPPFLAGS"
    - export LDFLAGS="-L$HOME/miniconda/lib $LDFLAGS"
    - LDFLAGS="-L$HOME/miniconda/lib -Wl,-rpath,$HOME/miniconda/lib" ./configure --prefix=$HOME && make &&  make install
    - fwdppConfig --version
    - make check
    #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then make check; fi
    #For some reason, make check on OS X + conda fails to respect LD_LIBRARY_PATH,
    #so we'll run the tests manually
    #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then for i in $(find testsuite -type f -perm +111);do $i -r detailed;done; fi
